# Site settings
title: Rick Hanolt Web Development & Design
header-img: img/home-bg.png
email: rhanolt@gmail.com
copyright_name: RickHanolt
description: > # this means to ignore newlines until "baseurl:"
  A Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RickHanolt
learn_profile: RickHanolt
email_username: rhanolt@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
